### ISSUE TITLE
enable to cache cargo's registry and build in gitlab ci

### ISSUE THREAD

**Issue by fengqi2019** [messense/rust-musl-cross#42]
if somebody need, it is my ci's script that can enable to cache.

1. because ci's cache only can use paths that are in the local working copy, so we must mkdir a folder in our project for cargo's registry (it is "target/registry" in my script), and it is my project structure:
```
.
├── Cargo.toml
├── src
│       ├── main.rs
├── target
│   └── registry
```
2. the script:
```
build-job:
  stage: build
  only:
    refs:
      - master
  tags:
    - maven
  image: messense/rust-musl-cross:x86_64-musl
  script:
    - ln -s $(pwd)/target/registry /root/.cargo/registry
    - export CARGO_BUILD_DEP_INFO_BASEDIR=.
    - cargo build --package endpoint --bin endpoint --release --target=x86_64-unknown-linux-musl
  cache:
    key: moss-endpoint-cache
    paths:
      # cache for cargo registry
      - target/registry/
      # cache for build
      - target/x86_64-unknown-linux-musl/
      - target/release/
```
