### ISSUE TITLE
Private git repository

### ISSUE THREAD

**Issue by xoac** [messense/rust-musl-cross#7]
Hi, 
I would like to use this when and have no idea how to manage it.

```toml
[dependencies]
package = { git = "https://@git.private.com/repo/repo.git" }
```

**Comment by xoac** [comment]
Ok The workaround if sb is looking:
```
# inside my project
$ git submodule add https://@git.private.com/repo/repo.git
```
Then edit `Cargo.toml`
```toml
[dependencies]
package = { path = "repo" }
```
Now it can be easy passed to docker container 👍 but it would be nice to could use `git =
` in with cargo. So I left it still open.
